-- Your SQL goes here
CREATE TABLE IF NOT EXISTS genres (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  title VARCHAR NOT NULL,
  parent_id VARCHAR(36) NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);
